typedef enum {
	OBANavigationTargetTypeRoot=0,
	OBANavigationTargetTypeSearch,
	OBANavigationTargetTypeSearchResults,
	OBANavigationTargetTypeBookmarks,
	OBANavigationTargetTypeRecentStops,
	OBANavigationTargetTypeStop,
	OBANavigationTargetTypeEditBookmark,
	OBANavigationTargetTypeEditStopPreferences,
	OBANavigationTargetTypeSettings,
	OBANavigationTargetTypeContactUs,
	OBANavigationTargetTypeAgencies
} OBANavigationTargetType;