coverage:
  status:
    project: off
    patch: off
  ignore:
    - cmake-debug-build/*
    - Example/*
    - Scripts/*
    - Documentaion/*
    - Tests/*
    - Pods/*
    - Applications/Xcode.app/*
    - vendor/*
    - Carthage/*
    - build/*
    - .build/*
    - .vagrant/*

