os: osx
language: objective-c
matrix:
  include:                                              
    - {osx_image: xcode8.2, env: 'PLAT=macOS    SWFT=3.0  DST="arch=x86_64"'}
    - {osx_image: xcode8.2, env: 'PLAT=iOS      SWFT=3.0  DST="OS=9.3,name=iPhone SE"'}
    - {osx_image: xcode8.2, env: 'PLAT=iOS      SWFT=3.0  DST="OS=10.2,name=iPhone SE"'}
    - {osx_image: xcode8.2, env: 'PLAT=tvOS     SWFT=3.0  DST="OS=9.2,name=Apple TV 1080p"'}
    - {osx_image: xcode8.2, env: 'PLAT=tvOS     SWFT=3.0  DST="OS=10.1,name=Apple TV 1080p"'}
    - {osx_image: xcode8.2, env: 'PLAT=watchOS  SWFT=3.0  DST="OS=3.1,name=Apple Watch - 38mm"'}

    - {osx_image: xcode8.3, env: 'PLAT=macOS    SWFT=3.1  DST="arch=x86_64"'}
    - {osx_image: xcode8.3, env: 'PLAT=iOS      SWFT=3.0  DST="OS=9.3,name=iPhone SE"'}
    - {osx_image: xcode8.3, env: 'PLAT=iOS      SWFT=3.1  DST="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode8.3, env: 'PLAT=tvOS     SWFT=3.0  DST="OS=9.2,name=Apple TV 1080p"'}
    - {osx_image: xcode8.3, env: 'PLAT=tvOS     SWFT=3.1  DST="OS=10.2,name=Apple TV 1080p"'}
    - {osx_image: xcode8.3, env: 'PLAT=watchOS  SWFT=3.1  DST="OS=3.2,name=Apple Watch - 38mm"'}

    - {osx_image: xcode9,   env: 'PLAT=macOS    SWFT=3.2  DST="arch=x86_64"'}
    - {osx_image: xcode9,   env: 'PLAT=iOS      SWFT=3.2  DST="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode9,   env: 'PLAT=iOS      SWFT=3.2  DST="OS=11.0,name=iPhone SE"'}
    - {osx_image: xcode9,   env: 'PLAT=tvOS     SWFT=3.2  DST="OS=10.2,name=Apple TV 1080p"'}
    - {osx_image: xcode9,   env: 'PLAT=tvOS     SWFT=3.2  DST="OS=11.0,name=Apple TV 1080p"'}
    - {osx_image: xcode9,   env: 'PLAT=watchOS  SWFT=3.2  DST="OS=3.2,name=Apple Watch - 38mm"'}
    - {osx_image: xcode9,   env: 'PLAT=watchOS  SWFT=3.2  DST="OS=4.0,name=Apple Watch - 38mm"'}

    - {osx_image: xcode9,   env: 'PLAT=macOS    SWFT=4.0  DST="arch=x86_64"'}
    - {osx_image: xcode9,   env: 'PLAT=iOS      SWFT=4.0  DST="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode9,   env: 'PLAT=iOS      SWFT=4.0  DST="OS=11.0,name=iPhone SE"'}
    - {osx_image: xcode9,   env: 'PLAT=tvOS     SWFT=4.0  DST="OS=10.2,name=Apple TV 1080p"'}
    - {osx_image: xcode9,   env: 'PLAT=tvOS     SWFT=4.0  DST="OS=11.0,name=Apple TV 1080p"'}
    - {osx_image: xcode9,   env: 'PLAT=watchOS  SWFT=4.0  DST="OS=3.2,name=Apple Watch - 38mm"'}
    - {osx_image: xcode9,   env: 'PLAT=watchOS  SWFT=4.0  DST="OS=4.0,name=Apple Watch - 38mm"'}
install:
  - carthage bootstrap --platform $PLAT
script:
  - set -o pipefail
  - xcodebuild -scheme PMKCoreLocation -quiet -destination "$DST" build SWIFT_VERSION=$SWFT
  - if [ "$PLAT" != "watchOS" ]; then
      xcodebuild -scheme PMKCoreLocation -quiet -destination "$DST" test;
    fi
